# Generated by Django 3.2 on 2024-03-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_number',
            field=models.IntegerField(),
        ),
    ]
